import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity()
export class Reminder {
    @PrimaryGeneratedColumn()
    id!: number;
    
    // UUID string
    @Column({ type: 'varchar'})
    userId!: string;
    
    @Column({ type: 'varchar' })
    title!: string;
    
    @Column({ type: 'text', nullable: true },)
    message?: string | null;
    
    @Column({ type: 'timestamp' })
    createdAt!: Date;

    @Column({ type: 'timestamp' })
    reminderTime!: Date;

    @Column({ type: 'varchar' })
    status!: 'active' | 'disabled' | 'canceled'; // Lleva el control del estado del recordatorio, es distinto a los status de las notificaciones.
}

/**
 * 
 * create table public.recordatorios (
  r_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp without time zone null,
  user_id bigint not null,
  r_title character varying not null,
  r_description character varying null,
  r_reminder_time timestamp without time zone not null,
  r_status character varying not null,
  constraint recordatorios_pkey primary key (r_id),
  constraint recordatorios_user_id_fkey foreign KEY (user_id) references usuarios (u_id)
) TABLESPACE pg_default;
 */