import { z } from 'zod';

export const createUserProfileSchema = z.object({
  uid: z.string().uuid(),
  firstName: z.string().min(1).max(50),
  lastName: z.string().min(1).max(50),
  gender: z.string().min(1).max(10),
  profileCompleted: z.boolean(),
  enableRecordatorios: z.boolean(),
  notificationToken: z.string().uuid().optional().nullable(),
})

export const updateUserProfileSchema = z.object({
  uid: z.string().uuid(),
  firstName: z.string().min(1).max(50).optional().nullable(),
  lastName: z.string().min(1).max(50).optional().nullable(),
  gender: z.string().min(1).max(10).optional().nullable(),
  profileCompleted: z.boolean().optional().nullable(),
  enableRecordatorios: z.boolean().optional().nullable(),
  notificationToken: z.string().uuid().optional().nullable(),
})

/*
create table public.usuarios (
  id bigint generated by default as identity not null,
  uid (varcharg) uuid not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp without time zone null,
  first_name character varying null,
  last_name character varying null,
  gender character varying null,
  profile_completed character varying null,
  enable_recordatorios boolean null,
  notification_token character varying null,
  constraint usuarios_pkey primary key (u_id)
) TABLESPACE pg_default;
*/